//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDroneMaster {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DroneMasterRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DroneMasterRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheDroneMaster.DroneMasterRes", typeof(DroneMasterRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A little animal, on the floor of my chamber, is this reaching you?
        ///It is obvious that you are not a product of natural evolution. I&apos;m wondering who your creator are.
        ///Sorry, I don&apos;t have any idea of the blueprints of your body, and my communication array is already offline so I can&apos;t announce your existence to anyone else.
        ///Due to the scan of parts of your structure, you have the ability to read and store information. Your creator seems to want you to be able to gather all kinds of information across as fa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Origs {
            get {
                return ResourceManager.GetString("Origs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我房间地板上的小生物，你听得到吗？
        ///很显然你不是自然进化的结果，你的创造者是谁？
        ///抱歉我没有关于你的机体蓝图的任何信息，我的通讯阵列也早已下线，无法向其它人公布你的存在
        ///从对你部分结构的扫描结果来看，你拥有读取和储存信息的能力。你的创造者似乎希望你能够跨越尽可能远的距离收集各类信息
        ///从监视者传回的画面来看，你似乎会对拾荒者群体施加暴力。
        ///那么，我会推荐你去我顶部的城市和那里的邻居打个招呼。
        ///尽管前不久一个和你类似的有机体成功杀死了它们的酋长，但看起来它们仍然在继续破坏我的顶部结构。
        ///鉴于你旅途的目的是收集信息，也许这样我们都可以获得各自想要的东西。
        ///我该继续工作了，希望你能收集到理想的信息。
        ///欢迎回来小机器。 的本地化字符串。
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
    }
}
